---
title: "PHPT DXA"
author: "Ewa Zalewska"
date:  "`r format(Sys.time(), '%e %b %Y, godz. %H:%M')`"
output:
  html_document:
  code_folding: hide
---
  
  
```{r, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r setup, include=FALSE}
library(dplyr)
library(purrr)
library(ggpubr)
library(tidyr)
library(scales)
library(rstatix)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(mice)

plik_dane_do_analizy <- "PHPT.RDS"

if (file.exists(plik_dane_do_analizy)) {
  PHPT <- readRDS(plik_dane_do_analizy)
} else {
  stop(sprintf("Nie znaleziono pliku: `%s`. Uruchom notatnik przygotowujący zbiór danych!", plik_dane_do_analizy))
}

PHPT_ml <- PHPT

zmienne <- c("fracture", "nicotine_dependence")

PHPT_ml[zmienne] <- lapply(PHPT_ml[zmienne], function(x) ifelse(x == "Y", 1, 0))
PHPT_ml$sex <- ifelse(PHPT_ml$sex == "K", 1, 0)


# PHPT$fracture_bin <- ifelse(PHPT$fracture == "Y", 1, 0)
# PHPT$nicotine_dependence_bin <- ifelse(PHPT$nicotine_dependence == "Y", 1, 0)

```


# algorytm MICE 
``` {r}

kolumny_do_imputacji <- c("TBS", "Tscore_lumbar", "Tscore_femur_neck", "Tscore_radial")
dane_subset <- PHPT_ml[, kolumny_do_imputacji]

imputacja <- mice(dane_subset, m = 5, method = 'pmm', seed = 123)

dane_imputowane <- complete(imputacja, 1)

PHPT_ml[, kolumny_do_imputacji] <- dane_imputowane

summary(PHPT_ml)

```



## Z jakimi cechami wiązało się występowanie zlamań w modelu logistycznym?
``` {r}
model <- glm(fracture ~ group + sex + age + BMI + nicotine_dependence + Ca + iPTH + Tscore_femur_neck + Tscore_radial + Tscore_lumbar + TBS, data = PHPT_ml, family = binomial)
summary(model)
# OR
exp(coef(model))
# przedziały ufności 95%:
exp(confint(model))
BIC(model)
```

## Model 0 

```{r}
model0 <- glm(fracture ~ 1, data = PHPT_ml, family = binomial)
summary(model0)
exp(coef(model0))
exp(confint(model0))
BIC(model0)
```


## Model 1 

```{r}
model1 <- glm(fracture ~ age, data = PHPT_ml, family = binomial)
summary(model1)
exp(coef(model1))
exp(confint(model1))
BIC(model0, model1)
```

## Model 2

```{r}
model2 <- glm(fracture ~ age + sex, data = PHPT_ml, family = binomial)
summary(model2)
exp(coef(model2))
exp(confint(model2))
BIC(model0, model1, model2)
```

## Model 3

```{r}
model3 <- glm(fracture ~ age * sex , data = PHPT_ml, family = binomial)
summary(model3)
exp(coef(model3))
exp(confint(model3))
BIC(model0, model1, model2, model3)
```

## Model 4

```{r}
model4 <- glm(fracture ~ age + sex + group, data = PHPT_ml, family = binomial)
summary(model4)
exp(coef(model4))
exp(confint(model4))
BIC(model0, model1, model2, model3, model4)
```

## Model 5

```{r}
model5 <- glm(fracture ~ age + sex + group + TBS, data = PHPT_ml, family = binomial)
summary(model5)
exp(coef(model5))
exp(confint(model5))
BIC(model0, model1, model2, model3, model4, model5)
```

## Model 5B

```{r}
model5B <- glm(fracture ~ age * sex + TBS, data = dplyr::filter(PHPT_ml, group=="B"), family = binomial)
summary(model5B)
exp(coef(model5B))
exp(confint(model5B))
BIC(model5B)
```


## Model 5K

```{r}
model5K <- glm(fracture ~ age * sex + TBS, data = dplyr::filter(PHPT_ml, group=="K"), family = binomial)
summary(model5K)
exp(coef(model5K))
exp(confint(model5K))
BIC(model5K)
```

## Model 6

```{r}
model6 <- glm(fracture ~ age + sex + group + TBS + BMI + nicotine_dependence + Ca + iPTH, data = PHPT_ml, family = binomial)
summary(model6)
exp(coef(model6))
exp(confint(model6))
BIC(model0, model1, model2, model3, model4, model5, model6)
```


## Model 7

```{r}
model7 <-  glm(fracture ~ age + sex + group + TBS + BMI + nicotine_dependence + Ca + iPTH + BMD_neck, data = PHPT_ml, family = binomial)
summary(model7)
exp(coef(model7))
exp(confint(model7))
BIC(model0, model1, model2, model3, model4, model5, model6, model7)
```

## Model 8

```{r}
model8 <- glm(fracture ~ age + sex + TBS + nicotine_dependence + BMI + Ca + iPTH + Tscore_femur_neck + Tscore_radial + Tscore_lumbar, data = PHPT_ml, family = binomial)
summary(model8)
exp(coef(model8))
exp(confint(model8))
BIC(model0, model1, model2, model3, model4, model5, model6, model7, model8)
```

## Model 9

```{r}
model9 <- glm(fracture ~ age + sex + TBS + Tscore_femur_neck + Tscore_radial + Tscore_lumbar, data = PHPT_ml, family = binomial)
summary(model9)
exp(coef(model9))
exp(confint(model9))
BIC(model0, model1, model2, model3, model4, model5, model6, model7, model8, model9)
```


```{r}
model10 <- glm(fracture ~ age + sex + BMI + nicotine_dependence + TBS + Tscore_femur_neck + Tscore_radial + Tscore_lumbar, data = PHPT_ml, family = binomial)
summary(model10)
exp(coef(model10))
exp(confint(model10))
BIC(model0, model1, model2, model3, model4, model5, model6, model7, model8, model9, model10)
```

colSums(is.na(PHPT_ml[, c("age", "sex", "BMI", TBS", "Tscore_femur_neck", "Tscore_lumbar", "T_score_radial")]))

