---
title: "PHPT DXA"
author: "Ewa Zalewska, Lukasz Cieszynski, Monika Berendt - Obolonczyk, Julia Tarnowska, Bartosz Zeglen, Renata Swiatkowska-Stodulska"
date:  "`r format(Sys.time(), '%e %b %Y, godz. %H:%M')`"
output:
  html_document:
    code_folding: hide
---

```{r, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(writexl)
library(psych)
library(lavaan)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(rstatix)
library(modelr)
library(broom)


PHPT <- read_delim("PNP_densytometria_10_04_25.csv", delim = ";", 
                  escape_double = FALSE,locale = locale(decimal_mark = "."), trim_ws = TRUE)

# Usunięcie wierszy z brakami danych (więcej niż 20 braków w danych)
PHPT <- PHPT %>%
  filter(rowSums(is.na(.)) <= 20)

# Usunięcie kolumn z brakami danych
PHPT <- PHPT %>%
  select(where(~ !all(is.na(.))))

# nowy sposb, wszystkie kolumny z datami razem:
PHPT[c("birthdate", "hosp_date", "DXA_date")] <- lapply(PHPT[c("birthdate", "hosp_date", "DXA_date")], as.Date, format = "%d.%m.%Y")

# sprawdzenie czy udało się zmienić wartości na daty:
sapply(PHPT$birthdate, inherits, what = "Date")

# nowa wersja przy pomocy pakietu tidyvierse:
PHPT <- PHPT %>%
  mutate(across(
    where(~ is.character(.) && all(grepl("^[-]?[0-9]+(\\.[0-9]+)?$", .[!is.na(.)]))),
    ~ as.numeric(gsub("−", "-", .))
  ))


# sprawdzenie czy udało się zmienić wartości na cyfry:
sapply(PHPT$HF_risk, is.numeric)
sapply(PHPT$Tscore_femur_neck, is.numeric)
sapply(PHPT$Tscore_femur_total, is.numeric)


PHPT <- PHPT %>%
  mutate(log_iPTH = log(iPTH),
         log_Ca = log(Ca),
         log_BMD = log(BMD_neck),
         log_MOF = log(MOF_risk),
         log_HF = log(HF_risk),
         log_TBS = log(TBS))

PHPT <- PHPT %>%
  mutate(age_split = case_when (age >= 50 ~ "older",
                                age < 50 ~ "younger"))


PHPT <- PHPT %>%
  mutate(TBS_split = case_when (TBS >= 1.2 ~ "high",
                                TBS < 1.2 ~ "low"))
```

# sprawdzenie rozkladu - w obu grupach (PHPT i kontrolnej)
```{r}
PHPT %>%
  select(age, weight, Ca, Pi, iPTH, nOHD, aOHD, Cr, albumin, BMD_neck, HF_risk, MOF_risk, Tscore_femur_neck, Tscore_femur_total, Tscore_lumbar, Tscore_radial, zscore_femur_neck, zscore_femur_total, zscore_lumbar, zscore_radial) %>%
  map(shapiro.test)
```
# sprawdzenie rozkladu w grupie PHPT:
```{r}
PHPT %>%
  filter(group == "B") %>%
  select(age, weight, Ca, Pi, iPTH, nOHD, aOHD, Cr, albumin, BMD_neck, HF_risk, MOF_risk, Tscore_femur_neck, Tscore_femur_total, Tscore_lumbar, Tscore_radial, zscore_femur_neck, zscore_femur_total, zscore_lumbar, zscore_radial) %>%
  map(shapiro.test)
```
# sprawdzenie rozkladu w grupie kontrolnej:
```{r}
PHPT %>%
  filter(group == "K") %>%
  select(nOHD, BMD_neck, Tscore_femur_neck, Tscore_femur_total, Tscore_lumbar, Tscore_radial, zscore_femur_neck, zscore_femur_total, zscore_lumbar, zscore_radial) %>%
  map(shapiro.test)
```
# Rozklad normalny maja zmienne: Tscore_femur_neck, Tscore_femur_total, Tscore_lumbar, Tscore_radial, zscore_femur_neck, zscore_femur_total, zscore_lumbar, zscore_radial

```{r setup, include=FALSE}
# Zapisz lokalnie zbiór danych przeznaczony do analizy danych dotyczących PHPT
plik_dane_do_analizy <- "PHPT.RDS"
saveRDS(PHPT, plik_dane_do_analizy)
```

















